{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mojang",
    "module": "datafixerupper",
    "version": "9.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.2-jre"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.12"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "datafixerupper-9.0.19.jar",
          "url": "datafixerupper-9.0.19.jar",
          "size": 731440,
          "sha512": "f44d53151722c2884e57bd8dd567dea370c144dc82d73a96f21955d5036d413aeb45fb8b92d11e1ce049139ed479774aad65f108235b102773192acfa994600b",
          "sha256": "9653a39cf5c4853cc98628d902dcb23ffeb2755122ecc563bde38c8f60c0b61e",
          "sha1": "4e91f9712fa1e83231d1501625381b0210a977da",
          "md5": "99001e76cd0306a0f3383311b055b3ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.2-jre"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.12"
          }
        }
      ],
      "files": [
        {
          "name": "datafixerupper-9.0.19.jar",
          "url": "datafixerupper-9.0.19.jar",
          "size": 731440,
          "sha512": "f44d53151722c2884e57bd8dd567dea370c144dc82d73a96f21955d5036d413aeb45fb8b92d11e1ce049139ed479774aad65f108235b102773192acfa994600b",
          "sha256": "9653a39cf5c4853cc98628d902dcb23ffeb2755122ecc563bde38c8f60c0b61e",
          "sha1": "4e91f9712fa1e83231d1501625381b0210a977da",
          "md5": "99001e76cd0306a0f3383311b055b3ab"
        }
      ]
    }
  ]
}
